// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package throttle

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockActivator is an autogenerated mock type for the Activator type
type MockActivator struct {
	mock.Mock
}

// Activate provides a mock function with given fields: ctx
func (_m *MockActivator) Activate(ctx context.Context) (Result, error) {
	ret := _m.Called(ctx)

	var r0 Result
	if rf, ok := ret.Get(0).(func(context.Context) Result); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(Result)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
